#!/bin/sh
# Switch the active sprite and regenerate the portraits.
#
#   ./tools/use-sprite.sh drawn      the sprite generated by draw-sprite.py
#   ./tools/use-sprite.sh <file>     any sprite.json with the same shape
#
# The active sprite is skills/shiba/assets/sprite.json. Keep a copy of the one
# you replace: the portraits in assets/faces/ are derived from it.
set -e
here=$(cd "$(dirname "$0")/.." && pwd)
target=$1
[ -n "$target" ] || { echo "usage: use-sprite.sh drawn|<path to sprite.json>"; exit 1; }
[ "$target" = "drawn" ] && target="$here/skills/shiba/assets/sprite-drawn.json"
[ -f "$target" ] || { echo "not found: $target"; exit 1; }

python3 - "$target" "$here" <<'PY'
import json, shutil, sys
src, here = sys.argv[1], sys.argv[2]
d = json.load(open(src))
need = {"w", "h", "pal", "rows", "moods"}
missing = need - set(d)
if missing:
    raise SystemExit("sprite is missing keys: %s" % ", ".join(sorted(missing)))
if len(d["rows"]) != d["h"] or any(len(r) != d["w"] for r in d["rows"]):
    raise SystemExit("rows do not match the declared w/h")
shutil.copy(src, here + "/skills/shiba/assets/sprite.json")
print("active sprite: %s (%dx%d, %d moods)" % (src, d["w"], d["h"], len(d["moods"])))
PY
python3 "$here/skills/shiba/scripts/build-faces.py" >/dev/null
echo "portraits regenerated"
